services:
    docs:
        image: ghcr.io/typo3-documentation/render-guides:latest
        pull_policy: always
        profiles: ["manual"]
        command: ["--config=Documentation"]
        volumes:
            - ../:/project
