version: "3.6"
services:
    web:
        environment:
            - EXTENSION_KEY=dce
            - PACKAGE_NAME=t3/dce

            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_PORT=3306
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=Password:joh316
            - TYPO3_INSTALL_SITE_NAME=EXT:dce Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/dce
              consistency: cached
            - v12-data:/var/www/html/v12
volumes:
    v12-data:
        name: "${DDEV_SITENAME}-v12-data"
