services:
    web:
        environment:
            - EXTENSION_KEY=dce
            - PACKAGE_NAME=t3/dce

            # TYPO3 config
            - TYPO3_DB_DRIVER=mysqli
            - TYPO3_DB_USERNAME=root
            - TYPO3_DB_PASSWORD=root
            - TYPO3_DB_HOST=db
            - TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
            - TYPO3_SETUP_ADMIN_USERNAME=admin
            - TYPO3_SETUP_ADMIN_PASSWORD=Password:joh316
            - TYPO3_PROJECT_NAME=EXT:dce Dev Environment
            - TYPO3_SERVER_TYPE=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/dce
              consistency: cached
            - v14-data:/var/www/html/v14
            - v14-classic-data:/var/www/html/v14-classic
volumes:
    v14-data:
        name: "${DDEV_SITENAME}-v14-data"
    v14-classic-data:
        name: "${DDEV_SITENAME}-v14-classic-data"
